<a href="https://colab.research.google.com/github/dvillanueva123/Cd-202202_Darinel_Villanueva/blob/main/Taller1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pyproj

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyproj in /usr/local/lib/python3.7/dist-packages (3.2.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from pyproj) (2022.6.15)

In [ ]:
import pandas as pd

In [ ]:
ruta= "https://foscalinternacional.com/datasets/eventos_dengue_2020.csv"
df= pd.read_csv(ruta)

In [ ]:
df

,ID,fec_not,semana,año,edad_,uni_med_,sexo_,cod_pais_o,cod_dpto_o,cod_mun_o,...,aum_hematocrito,conducta,latitud,longitud,fec_not2,fec_hos_2,fecha_contagio2,inicio_sintomas2,x,y
0,1,17/01/2020,1,2020,25,1,F,170,68,276,...,2,1. Ambulatorio,7.076011,-73.102501,2020-01-17,NaT,2020-01-17,2020-01-10,709584.027559,782579.281866
1,2,10/01/2020,1,2020,24,1,M,170,68,276,...,2,1. Ambulatorio,7.079495,-73.105400,2020-01-10,NaT,2020-01-10,2020-01-07,709262.121378,782963.354103
2,3,12/01/2020,1,2020,58,1,M,170,68,276,...,2,1. Ambulatorio,7.090290,-73.091003,2020-01-12,NaT,2020-01-12,2020-01-08,710847.924654,784163.825097
3,4,12/01/2020,1,2020,29,1,F,170,68,276,...,2,1. Ambulatorio,7.067435,-73.090958,2020-01-12,NaT,2020-01-10,2020-01-06,710863.366771,781635.895608
4,5,10/01/2020,1,2020,56,1,F,170,68,276,...,2,2. Hospitalizacion piso,7.066905,-73.104980,2020-01-10,2020-01-10,2020-01-10,2020-01-07,709314.159319,781570.969374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1257,1258,7/03/2020,9,2020,36,1,F,170,68,276,...,2,1. Ambulatorio,7.072610,-73.099487,2020-03-07,NaT,2020-03-06,2020-03-03,709918.546763,782204.438977
1258,1259,13/03/2020,9,2020,42,1,M,170,68,276,...,1,2. Hospitalizacion piso,7.065252,-73.103607,2020-03-13,2020-03-13,2020-03-13,2020-03-06,709466.644754,781388.734012
1259,1260,8/03/2020,9,2020,2,1,M,170,68,276,...,2,1. Ambulatorio,7.091391,-73.103264,2020-03-08,NaT,2020-03-08,2020-03-04,709492.782783,784279.996264
1260,1261,11/03/2020,9,2020,12,1,F,170,68,276,...,2,1. Ambulatorio,7.061083,-73.097000,2020-03-11,NaT,2020-03-11,2020-03-05,710198.574916,780930.648555
1261,1262,9/03/2020,9,2020,14,1,M,170,68,276,...,2,2. Hospitalizacion piso,7.062521,-73.080444,2020-03-09,2020-03-06,2020-03-06,2020-03-02,712027.277417,781097.169210

In [ ]:
df.dtypes

ID                     int64
fec_not               object
semana                 int64
año                    int64
edad_                  int64
uni_med_               int64
sexo_                 object
cod_pais_o             int64
cod_dpto_o             int64
cod_mun_o              int64
area_                  int64
ocupacion_             int64
tip_ss_               object
cod_ase_              object
gp_discapa             int64
gp_desplaz             int64
gp_migrant             int64
gp_carcela             int64
gp_gestan              int64
gp_calle               int64
gp_psiquia             int64
gp_vic_vio             int64
fecha_contagio        object
inicio_sintomas       object
pac_hos_               int64
fec_hos_              object
condicion_final        int64
fecha_defuncion      float64
fecha_nacimiento      object
certif_defuncion     float64
familiar_sintomas      int64
fiebre                 int64
cefalea                int64
dolor_retroocular      int64
mialgias               int64
artralgia              int64
erupcion               int64
dolor_abdomen          int64
vomito                 int64
diarrea                int64
somnolencia            int64
hipotension            int64
hepatomegalia          int64
hemorragia_mucosa      int64
hipotermia             int64
caida_plaquetas        int64
acum_liquido           int64
aum_hematocrito        int64
conducta              object
latitud              float64
longitud             float64
dtype: object

In [ ]:
from datetime import datetime
df['fec_not2'] = pd.to_datetime(df['fec_not'],format="%d/%m/%Y")

In [ ]:
df['fec_hos_2'] = pd.to_datetime(df['fec_hos_'],format="%d/%m/%Y")   
df['fecha_contagio2'] = pd.to_datetime(df['fecha_contagio'],format="%d/%m/%Y")   
df['inicio_sintomas2'] = pd.to_datetime(df['inicio_sintomas'],format="%d/%m/%Y")

In [ ]:
import pyproj
P =pyproj.Proj(proj='utm',zone=18,ellps='WGS84',preserve_units=True)

In [ ]:
df['x'],df['y']= P(df['longitud'], df['latitud'])

In [ ]:
df

,ID,fec_not,semana,año,edad_,uni_med_,sexo_,cod_pais_o,cod_dpto_o,cod_mun_o,...,aum_hematocrito,conducta,latitud,longitud,fec_not2,fec_hos_2,fecha_contagio2,inicio_sintomas2,x,y
0,1,17/01/2020,1,2020,25,1,F,170,68,276,...,2,1. Ambulatorio,7.076011,-73.102501,2020-01-17,NaT,2020-01-17,2020-01-10,709584.027559,782579.281866
1,2,10/01/2020,1,2020,24,1,M,170,68,276,...,2,1. Ambulatorio,7.079495,-73.105400,2020-01-10,NaT,2020-01-10,2020-01-07,709262.121378,782963.354103
2,3,12/01/2020,1,2020,58,1,M,170,68,276,...,2,1. Ambulatorio,7.090290,-73.091003,2020-01-12,NaT,2020-01-12,2020-01-08,710847.924654,784163.825097
3,4,12/01/2020,1,2020,29,1,F,170,68,276,...,2,1. Ambulatorio,7.067435,-73.090958,2020-01-12,NaT,2020-01-10,2020-01-06,710863.366771,781635.895608
4,5,10/01/2020,1,2020,56,1,F,170,68,276,...,2,2. Hospitalizacion piso,7.066905,-73.104980,2020-01-10,2020-01-10,2020-01-10,2020-01-07,709314.159319,781570.969374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1257,1258,7/03/2020,9,2020,36,1,F,170,68,276,...,2,1. Ambulatorio,7.072610,-73.099487,2020-03-07,NaT,2020-03-06,2020-03-03,709918.546763,782204.438977
1258,1259,13/03/2020,9,2020,42,1,M,170,68,276,...,1,2. Hospitalizacion piso,7.065252,-73.103607,2020-03-13,2020-03-13,2020-03-13,2020-03-06,709466.644754,781388.734012
1259,1260,8/03/2020,9,2020,2,1,M,170,68,276,...,2,1. Ambulatorio,7.091391,-73.103264,2020-03-08,NaT,2020-03-08,2020-03-04,709492.782783,784279.996264
1260,1261,11/03/2020,9,2020,12,1,F,170,68,276,...,2,1. Ambulatorio,7.061083,-73.097000,2020-03-11,NaT,2020-03-11,2020-03-05,710198.574916,780930.648555
1261,1262,9/03/2020,9,2020,14,1,M,170,68,276,...,2,2. Hospitalizacion piso,7.062521,-73.080444,2020-03-09,2020-03-06,2020-03-06,2020-03-02,712027.277417,781097.169210

Alcaldia= 7.062959926538416, -73.08617846553514
X=711393,5   Y = 781143,1

In [ ]:
import numpy as np

df['distancia'] = np.sqrt((pow(df['x'],2) - pow(711393.5,2))+(pow(df['y'],2) - pow(781143.1,2)))

/usr/local/lib/python3.7/dist-packages/pandas/core/arraylike.py:364: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [ ]:
df

,ID,fec_not,semana,año,edad_,uni_med_,sexo_,cod_pais_o,cod_dpto_o,cod_mun_o,...,conducta,latitud,longitud,fec_not2,fec_hos_2,fecha_contagio2,inicio_sintomas2,x,y,distancia
0,1,17/01/2020,1,2020,25,1,F,170,68,276,...,1. Ambulatorio,7.076011,-73.102501,2020-01-17,NaT,2020-01-17,2020-01-10,709584.027559,782579.281866,NaN
1,2,10/01/2020,1,2020,24,1,M,170,68,276,...,1. Ambulatorio,7.079495,-73.105400,2020-01-10,NaT,2020-01-10,2020-01-07,709262.121378,782963.354103,NaN
2,3,12/01/2020,1,2020,58,1,M,170,68,276,...,1. Ambulatorio,7.090290,-73.091003,2020-01-12,NaT,2020-01-12,2020-01-08,710847.924654,784163.825097,62868.291338
3,4,12/01/2020,1,2020,29,1,F,170,68,276,...,1. Ambulatorio,7.067435,-73.090958,2020-01-12,NaT,2020-01-10,2020-01-06,710863.366771,781635.895608,4018.084096
4,5,10/01/2020,1,2020,56,1,F,170,68,276,...,2. Hospitalizacion piso,7.066905,-73.104980,2020-01-10,2020-01-10,2020-01-10,2020-01-07,709314.159319,781570.969374,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1257,1258,7/03/2020,9,2020,36,1,F,170,68,276,...,1. Ambulatorio,7.072610,-73.099487,2020-03-07,NaT,2020-03-06,2020-03-03,709918.546763,782204.438977,NaN
1258,1259,13/03/2020,9,2020,42,1,M,170,68,276,...,2. Hospitalizacion piso,7.065252,-73.103607,2020-03-13,2020-03-13,2020-03-13,2020-03-06,709466.644754,781388.734012,NaN
1259,1260,8/03/2020,9,2020,2,1,M,170,68,276,...,1. Ambulatorio,7.091391,-73.103264,2020-03-08,NaT,2020-03-08,2020-03-04,709492.782783,784279.996264,47009.220804
1260,1261,11/03/2020,9,2020,12,1,F,170,68,276,...,1. Ambulatorio,7.061083,-73.097000,2020-03-11,NaT,2020-03-11,2020-03-05,710198.574916,780930.648555,NaN
1261,1262,9/03/2020,9,2020,14,1,M,170,68,276,...,2. Hospitalizacion piso,7.062521,-73.080444,2020-03-09,2020-03-06,2020-03-06,2020-03-02,712027.277417,781097.169210,28816.263004

In [ ]:
df['distancia']=